### ISSUE TITLE
About installing XDP

### ISSUE THREAD

**Issue by JIESUN233** [GuyZilberman/GPUInitiatedKeyValueStoreAPI#1]
Hi, 
I'm trying to install XDP but it seems that our server can not find packages. Could you help me look at it? Thanks~
<img width="755" alt="1732106648864" src="https://github.com/user-attachments/assets/fb90cc4b-c70a-4c1e-b28b-517c7d30e740">

**Comment by GuyZilberman** [comment]
Hi, try this instead:

sudo apt-get install ./packages/ubuntu22.04/pliops-xdp-onhost_3.0.2.0.deb

**Comment by JIESUN233** [comment]
Thanks! It works
